### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by ronTohar1** [AIRI-Institute/pogema#24]
installing latest version using pip and the example doesn't work - seems you still implement the gym API instead of gymnasium.
pogema version - 1.1.6

**Comment by Tviskaron** [comment]
Thank you for pointing out the issue. It seems that the current version of pogema available on PyPI (version 1.1.6) still implements the gym API instead of gymnasium. The gymnasium version of pogema is currently only available in the GitHub repository due to some compatibility problems with the gymnasium framework, particularly with the new version of SampleFactory.

If you specifically need the gymnasium version of pogema, you can install it using the following command:

`pip3 install git+https://github.com/AIRI-Institute/pogema`

Please note that this command installs the latest version of pogema directly from the GitHub repository.

If you require further assistance or have any more questions, please let me know. We are actively working on fixing the compatibility issues and plan to update the PyPI version of pogema with the major release that includes gymnasium once these issues are resolved.

**Comment by ronTohar1** [comment]
Great thank you
